### ISSUE TITLE
pympsym prints automorphisms with 1-indexed arrays (missing `sequence_multiplex_apply`)

### ISSUE THREAD

**Issue by goens** [Time0o/mpsym#19]
The code for `automorphisms` in pympsym is missing the conversion function of the sequence (`sequence_multiplex_apply`), basically here:  https://github.com/Time0o/mpsym/blob/395a5bdd864e30661f6e4a6621603b5506e7020a/python/pympsym.cpp#L318

I tried to understand how `sequence_multiplex_apply` is used in `orbit`, but it was pretty confusing and thought you'll probably figure it out and fix it much faster than I would get your code there. 

(other functions are missing this conversion too, like `expand_automorphisms`)

**Comment by Time0o** [comment]
This is sort of intentional (I think), permutations are displayed as 1 indexed but are actually 0-indexed in Python. This is arguably confusing. Currently we have this whole messy situation:

|                                 | C++           | Python |
| -------------------------- | ------------- | ------------ |
| processors indices   | 0 indexed | 0 indexed |
| task mappings          | 1 indexed | 0 indexed |
| permutations            | 1 indexed | 0 indexed |

My suggestion to remedy this would be to instead do this:

|                                 | C++           | Python |
| -------------------------- | ------------- | ------------ |
| processors indices   | 0 indexed | 0 indexed |
| task mappings          | 0 indexed | 0 indexed |
| permutations            | 1 indexed | 1 indexed |

Then at least the C++ and Python interfaces would match and no conversion is necessary inside pykpn (because Permutations will probably not need to be used directly). Additionally, inside `pympsym.cpp` all those weird conversions functions like `sequence_apply` could be removed. The only downside I see is that the mismatch between task mappings and permutations in the C++ code might lead to a (slight) loss of performance. Ideally, everything should be zero indexed everywhere, but making C++ permutations 0 indexed will break a lot of stuff and fixing that might take a lot of time.

I will prepare a commit implementing this and push it onto a branch created for this purpose, you can then test whether that breaks anything inside pykpn.

**Comment by goens** [comment]
I guess that suggestion works too, yes. The action on the architecture/mappings is, after all, something different than the permutation group. Would be nice if we had a way of making this very clear, but I'm happy with that solution.

**Comment by goens** [comment]
Although, just for completeness, we could have everything be 1-indexed in C++ and just expose it all as 0-indexed in python (pympsym), since you already have the conversion functions. That way we don't lose the performance if not necessary, and outputs are consistent.

**Comment by Time0o** [comment]
I guess since the conversion has to take place at some point between Python and C++ anyways the overhead is always going to be there unless the C++ interface is used directly. So I will implement the 0/0/1 approach for now.

**Comment by Time0o** [comment]
This has been fixed for some time, now everything is zero indexed.
